# Generated by Django 4.0.5 on 2022-06-24 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0002_alter_author_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Черновик'), ('p', 'Опубликовано'), ('w', 'в архиве')], default='d', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.post', verbose_name='Заголовок поста'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(help_text='Введите здесь текст своего комментария', verbose_name='Текст поста'),
        ),
    ]
